AS-42 - Retours recette disponibilités fiche AM
departement-loire-atlantique/jAssmat pull request #36
Opened 2023-01-10 10:49 UTC by LChoquet

2023-01-10 13:27 UTC, mformont approved these changes

2023-01-11 10:22 UTC, sguellec requested changes
L'encodage des caractère a sauté. Pas dramatique pour les commentaire mais il y a des libellés en dur pour lesquels ça va poser problème.

2023-01-13 11:42 UTC, sguellec commented on plugins/AssmatPlugin/jsp/include/displayDisponibilites.jspf
> +	      <th scope="row">Avant l'�cole</th>
Remettre les accents

2023-01-13 11:43 UTC, sguellec requested changes
Remettre les accents au moins sur la partie visible. Pas forcémeent dans les commentaires.

2023-01-13 11:43 UTC, sguellec commented on plugins/AssmatPlugin/jsp/include/displayDisponibilites.jspf
> +	      <th scope="row">Apr�s midi</th>
Remettre les accents

2023-01-13 11:43 UTC, sguellec commented on plugins/AssmatPlugin/jsp/include/displayDisponibilites.jspf
> +	      <th scope="row">Apr�s l'�cole</th>
Remettre les accents

2023-01-13 11:43 UTC, sguellec commented on plugins/AssmatPlugin/jsp/include/displayDisponibilites.jspf
> +	    <p><img src='<%= channel.getProperty("jcmsplugin.assmat.profil.logo.creneauDispo") %>' class="creneauDispo mrs" alt="Cr�neau disponible"><img src='<%= channel.getProperty("jcmsplugin.assmat.prof
Remettre les accents

2023-01-16 10:25 UTC, sguellec approved these changes

2023-01-17 08:15 UTC, merged